<?php

namespace ContainerQFVn4iT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalEditarFotoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AnimalEditarFotoController' shared autowired service.
     *
     * @return \App\Controller\AnimalEditarFotoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AnimalEditarFotoController.php';

        return $container->services['App\\Controller\\AnimalEditarFotoController'] = new \App\Controller\AnimalEditarFotoController();
    }
}
