<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerORbkGfy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerORbkGfy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerORbkGfy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerORbkGfy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerORbkGfy\App_KernelDevDebugContainer([
    'container.build_hash' => 'ORbkGfy',
    'container.build_id' => 'ef86a0f0',
    'container.build_time' => 1745417504,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerORbkGfy');
